# Generated by Django 4.1.7 on 2023-03-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousel_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='Design',
        ),
    ]
